var AnalyticsGraphDefaults = {
  missingDataGraphParams: {
    title: "Instant Article Views",
    animate_on_load: true,
    missing_is_zero: true,
    description: "Instant Articles for the requested page views",
    chart_type: 'missing-data',
    missing_text: 'Query for insights',
    target: '#chart',
    full_width: true,
    height: 300,
    x_label: 'Dates',
    y_label: 'Visitors',
    show_tooltips: true,
    right: 50,
    legend: ['All traffic', 'Android', 'IOS'],
  },
  dataGraphParams:{
    title: "Instant Article Views",
    animate_on_load: true,
    missing_is_zero: true,
    description: "Instant Articles for the requested page views",
    area: false,
    full_width: true,
    height: 300,
    target: '#chart',
    x_accessor: 'time',
    y_accessor: 'value',
    x_label: 'Dates',
    y_label: 'Visitors',
    show_tooltips: true,
    right: 50,
    legend: ['All traffic', 'Android', 'IOS'],
  },
  visitDurationGraphParams: {
    title: "Instant Article View Durations",
    animate_on_load: true,
    missing_is_zero: true,
    description: "Instant Articles for the requested page views",
    area: false,
    full_width: true,
    height: 300,
    target: '#chart',
    x_accessor: 'bucket',
    y_accessor: 'value',
    x_label: 'Duration in Seconds',
    y_label: 'Visitor Count',
    show_tooltips: true,
    right: 50,
  },
averageVisitDurationGraphParams:{
    title: "Instant Article View Durations",
    animate_on_load: true,
    description: "Instant Articles for the requested page views",
    area: false,
    full_width: true,
    height: 300,
    target: '#chart',
    x_accessor: 'date',
    y_accessor: 'value',
    x_label: 'Date',
    y_label: 'Average Visitor Duration',
    show_tooltips: true,
    left: 50,
  }
}
